### ISSUE TITLE
application.properties를 application.yml로 변경

### ISSUE THREAD

**Issue by choichanhyeok** [hyeoks-super-market/harmony-english-academy#9]
## a. 작업 내용 (Task Description)

> 1. 기존 application.properties 내용을 application.yml로 변경
```
# 기존
spring.application.name=harmony-english-academy
```

```
# yml 변경 내용
spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/hyeokDB
    username: root
    password: 1541
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8087
logging:
  level:
    org.springframework.cache: trace
```

.. DB설정, 프로필 설정, 레디스 설정, 포트 설정 등의 작업 진행

## b. 실행 배경

> 1. 가독성 향상
- 기호에 따라 다르겠지만 yml의 계층 구조가 가독성 측면에 이점이 있다고 판단해 적용키로함

## c. 목표

> 1. 최소한의 yml 작성 방법 및 구조 이해
- 물론 gpt나 레퍼런스를 통해 보겠지만 그럼에도 한번이라도 이해 하고 넘어가보기

## d. 추가 정보

> 1. application.yml 작성 참고 자료
- application.yml과 application.properties의 차이 [[참고 링크]](https://www.baeldung.com/spring-boot-yaml-vs-properties)
- application.yml example [[참고 링크]](https://dev.to/fullstackhacker/spring-boot-yaml-example-1kb2)
